server:
  port: 9002
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/olx-monitor"
  
  endpoint:
    shutdown:
      enabled: true
      
    info:
      enabled: true
      
    health:
      enabled: true


