management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/stock-monitor"
  
  endpoint:
    shutdown:
      enabled: true
      
    info:
      enabled: true
      
    health:
      enabled: true